### PR TITLE
Dev aaron

### PR DESCRIPTION
**Pull request by amendelson**
adds preliminary flood zones and updates intro text

### CODE REVIEW

**Comment by chrislkeller** [comment]
@amendelson: There seems to be a merge conflict here... I may incorporate locally and try to push and create a new pull request.

**Comment by chrislkeller** [comment]
@amendelson: So take a look here, pull this branch down and test locally. If things run as expected you can certainly merge this request and deploy.

There's an [array of strings](https://github.com/SCPR/static-projects/blob/1132ad3ebb19ed17c77fa7402492a44f350e6a63/maps/do-i-live-in-a-california-flood-zone/scripts/app.js#L6) that are the counties represented in new topojson you added. I'm not sure if they are all represented. If not, feel free to add what is missing following the established naming convention.

San Mateo County is in the array because [this example](http://projects.scpr.org/maps/do-i-live-in-a-california-flood-zone/#lat=37.61555930000001&lng=-122.39034400000003&zoom=20/) - basically San Fran Intl Airport - came up as San Mateo County and not San Francisco County

* [Here](https://github.com/SCPR/static-projects/blob/1132ad3ebb19ed17c77fa7402492a44f350e6a63/maps/do-i-live-in-a-california-flood-zone/scripts/app.js#L461) is where we determine if the lat/lng is in California, and if it's in one of the counties specified in the [array](https://github.com/SCPR/static-projects/blob/1132ad3ebb19ed17c77fa7402492a44f350e6a63/maps/do-i-live-in-a-california-flood-zone/scripts/app.js#L6).

* From there we [determine if the county found is one of those prelim counties](https://github.com/SCPR/static-projects/blob/1132ad3ebb19ed17c77fa7402492a44f350e6a63/maps/do-i-live-in-a-california-flood-zone/scripts/app.js#L352) and if so, [render a message](https://github.com/SCPR/static-projects/blob/1132ad3ebb19ed17c77fa7402492a44f350e6a63/maps/do-i-live-in-a-california-flood-zone/scripts/app.js#L401) that says the [zones are prelim](https://github.com/SCPR/static-projects/blob/1132ad3ebb19ed17c77fa7402492a44f350e6a63/maps/do-i-live-in-a-california-flood-zone/scripts/app.js#L417) for 100 and 500 zones.

**Comment by amendelson** [comment]
@chrislkeller Playing around and not getting it to break. That's good news. I recommend we make two edits before deploying

- Adding a message for no flood zone in a preliminary area. This determination (like being in a flood zone) is preliminary, so we should nod to that. We could have that as "But that doesn't mean that your area can't flood, _and flood maps in this area are still preliminary_. FEMA estimates that a third of Federal Disaster Assistance goes...

- Removing San Mateo from list of prelim counties. San Mateo County **is not** preliminary, with the exception of SFO. I think we can nod to SFO situation in the 'Sources' text.

- I can also add sentence to Sources about how Alpine County (population 1,100) has no digital flood map.

**Comment by amendelson** [comment]
@chrislkeller you mind checking out my last commit? it should address those bullet points

**Pull request merged**
